# Generated by Django 4.2.7 on 2025-11-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_locked_until_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
